### ISSUE TITLE
Expand plot_text Functionality

### ISSUE THREAD

**Issue by brichard1638** [hneth/ds4psy#1]
It is respectfully requested that the char_bg argument be expanded to allow entire words or alternatively, combinations of letters to be passed to this argument in a way that will be visually captured by the color set in the col_bg argument.

Currently, the char_bg argument accepts only a single character.

**Comment by hneth** [comment]
Thanks for this request, and for your interest in the `plot_text()` function!

As your request makes perfect sense, of course, I'd be happy to accommodate it.  As this will require a re-construction of the function, I must ask you for some patience.  But I'll see what I can do and get back to you asap.

Best,
Hans

**Comment by hneth** [comment]
The latest development version (**ds4psy** v0.6.0.9004) now includes a new `plot_text_match()` function.  
This function is modeled after `plot_text()`, but more general in accepting two regular expressions. These and the corresponding color arguments allow _highlighting_ and _de-emphasizing_ individual characters (i.e., the color of plotted text labels or the fill color of tiles), provided that they match the corresponding regex expressions.  

Perhaps you can check out `plot_text_match()` and let me know if this is what you were looking for?

PS:  The `plot_text()` and `plot_text_match()` were also revised to (invisibly) return a plot description (as a data frame of all characters and their properties).  Using and modifying this description should make it easy to create similar plots with different aesthetics.

**Comment by brichard1638** [comment]
Hans:::

The plot_text_match is awesome! I have tested various configurations of the function and it worked as you have documented it. However, there was one configuration response that I was unable to achieve. First, let me ensure that what I am trying to do relative to the function output is consistent with its capability.

The objective in one of the tests was to both colorize the text passed in the "lbl_hi" argument as well as to colorize the tiles associated with this text. To that end, I was unable to achieve this objective using the plot_text_match function in ds4psy  v0.6.0.9004. The code I used to test this configuration is as follows:

plot_text_match(file = "textfile.txt", lbl_hi = "wind", col_bg = "white", col_bg_hi = "cyan", col_lbl_hi = "red", borders = TRUE, border_col = "black")

Removing the col_bg argument colorized all the tiles except those represented by a space to gray:
plot_text_match(file = "textfile.txt", lbl_hi = "wind", col_bg_hi = "cyan", col_lbl_hi = "red", borders = TRUE, border_col = "black")

I realize that it is possible that I have misinterpreted the nature of the arguments used in this test. In addition, it is also possible that the ability to colorize both the col_lbl_hi of text and its associated tile may not have been a capability provided in this version of the function. If this is the case, I am hoping that you will consider adding the ability to colorize both the text and the tiles represented by the text.

My understanding of the arguments in the plot_text_match function is that the "col_bg_hi" argument represents the ability to colorize the tiles represented by text passed in the "lbl_hi" argument. Is this a correct assumption?

The challenge here when testing new functions in R is that the tester may or may not have clarity on the nature of a function's arguments. In any event, I look forward to your feedback on these observations.

**Comment by hneth** [comment]
Brice:::

Thanks for your enthusiasm — and for testing the new function!

The function should definitely be capable of handling the use case you describe.  But as it accepts a total of 4 regex strings (for both highlighting/de-emphasizing text labels, i.e., foreground, and the fill color of tiles, background), this should already be possible. 

For instance, highlighting the labels and tiles of the _same_ matches can be achieved by setting the `lbl_hi` and `bg_hi` arguments to the same regular expression:  

- `plot_text_match(file = "test.txt", lbl_hi = "te.t", bg_hi = "te.t",  col_bg = "white", col_bg_hi = "cyan", col_lbl_hi = "red",  borders = TRUE, border_col = "black")`

- `plot_text_match(file = "test.txt", lbl_hi = "te.t", bg_hi = "te.t",  col_bg_hi = "cyan", col_lbl_hi = "red",  borders = TRUE, border_col = "black")`

Adjusting the color arguments can only show effects when the corresponding regex arguments are used.  By default, the first 3 regex arguments (`lbl_hi`, `lbl_lo`, and `bg_hi`) are set to `NA` (i.e., unused), whereas `bg_lo` is initialized to `"[[:space:]]"` (to fill the tiles of space characters by `col_bg_lo = "white"`).

But as playing with multiple regex and color settings can get quite confusing, it's possible that I'm overlooking something here.  Hence, I'd be grateful if you could check out the function again.

Best,
Hans

**Comment by brichard1638** [comment]
Dr. Neth:::

Thank you for responding to my inquiry regarding the newly encoded plot_text_match function.

After having applied the sample code you provided, I was able to test it. I was able to get the expected results. The generated plot was exactly as I had imagined it to be!

The issue was what I thought it would be - which is, I did not understand the correct encoding and syntax supporting the function.

Thank you for your guidance and the effort expended on your part to address my inquiry and feedback.

The last question I have is related to function implementation. Are you going to replace the plot_text with the new code functionality of plot_text_match making a single function for text plotting, or, are you going to keep both plot_text and plot_text_match as separately defined functions?

I think what you have done with plot_text_match is a superior upgrade to plot_text. Since the plot_text function in its current form replicates the functionality you provided in plot_text_match, I would be inclined to believe that you would just update the plot_text function keeping it as the only function between the two.

I am interested in seeing what you ultimately decide.

However you decide to implement this newly added functionality, thank you for taking the time to redesign the plot_text function!

I look forward to the next version of ds4psy.

Warmest regards,

Brice Richard
Data Scientist
Washington, DC USA
________________________________

**Comment by hneth** [comment]
Thanks for testing the function and your feedback!

I agree that `plot_text_match()` is the superior function of two.  As its name is a bit awkward, I've now been re-naming it to `plot_chars()`.  This is not only shorter, but also describes more accurately what the function really does.

As I suspect that not many people are using the older `plot_text()` function, I'd like to incorporate its functionality as an option of `plot_chars()` and then re-direct the older function to the new one.  But until that's done, they may co-exist.  

Thanks again & best wishes,
Hans

PS:  Another reason for distinguishing between `plot_chars()` and `plot_text()` is that my **unikn** package also contains a `plot_text()` function that actually plots strings of text.  But as this function was designed for decorating small text elements (e.g., headings or titles), it currently does not provide any search or pattern matching functionality.  Ultimately, it may be desirable to combine both approaches, but that would require a lot of additional thought and time.

**Comment by hneth** [comment]
**P.P.S.:**  The `plot_chars()` function works, but mixes two distinct functionalities:

1. Generating a character map with matching patterns in text to aesthetic variables (e.g., colors or angle)
2. Plotting the character map (using the text and tile geoms from **ggplot2**).

Thus, `plot_chars()` will be replaced by more specialized functions:

1. `map_text_coord()` and `map_text_regex()` create character maps (as outputs, with optional pattern matching by using regular expressions)
2. `plot_charmap()` uses and plots such character maps (as inputs) 

By separating both parts, more flexible uses are possible (e.g., generating and plotting a variety of different character maps).

**Please note:**  The current development version (**ds4psy** v0.6.0.9014) still contains all of the above functions.  But the next release (v0.7.0) will probably remove plot_chars() to distinguish between functions with distinct functionalities.

**Comment by brichard1638** [comment]
Hans:::

Thank you for the update!

It sounds like you have moved to successfully extend the functionality of the original plot_text function in really interesting and compelling ways.

The specialized functions you have created really enhance the use cases for the original idea.

Thanks again for all of your hard work and thoughtfulness in re-engineering these functions.

I look forward to version v0.7.0 of the ds4psy package.

Warmest regards,

Brice Richard
Data Scientist
Washington, DC USA
________________________________

**Comment by hneth** [comment]
**P.S.**:  Just a quick note:  

I've started finalizing and checking the current version.  If all goes well, this should enable a CRAN release of **ds4psy** v0.7.0 tomorrow (May 12, 2021).  

Thanks for your patience and best wishes,
Hans

**Comment by brichard1638** [comment]
Hand:::This is great news!Thank you for providing the update.I look forward to the next version of ds4psy.Respectfully,BriceOn May 11, 2021 3:54 AM, Hansjörg Neth ***@***.***> wrote:
P.S.:  Just a quick note:
I've started finalizing and checking the current version.  If all goes well, this should enable a CRAN release of ds4psy v0.7.0 tomorrow (May 12, 2021).
Thanks for your patience and best wishes,
Hans

**Comment by brichard1638** [comment]
Hans:::

I was able to successfully download and test the new functions you've recently added to the ds4psy package (0.7.0)!

I will say that the functionality you added by way of the text plots has exceeded my expectations, in terms of the possibilities. Wow. You've done a great job with the choices you've made in crafting the functions supporting text plotting.

Personally, I'm interested in text plotting through the use and application of plot_chars. However, it is nice that this functionality has been substantially extended with the addition of plot_charmap. In addition, the mapping functions you've provided make the entire text plotting process transparent, as the underlying plotting framework is now directly visible to the user - very insightful!

I like this approach because it shows the thinking behind the framework. Because of this transparency, it's now possible to customize the tables created by map_text_coord and map_text_regex to further control the granularity of the text plot.

Either way, the options are now available to really apply flexible text plotting in ways that were previously unimaginable.

Thanks again for all of the work you have done on the ds4psy package. This package has matured into a remarkably compelling offering in the R environment.

I hope you get many downloads of this package as people around the world become more acclimated to the possibilities made available in R for text and data processing.

Warmest regards,

Brice
________________________________

**Comment by hneth** [comment]
Brice:::

Thanks for your positive comments and for your test and evaluation of the latest version!

It's feedback from ambitious and curious users or students that motivates this entire project.  So I can only hope that you and others will find the new functions useful — and I'm looking forward to seeing what you will do with them.

Thanks again and best wishes,
Hans

**Comment by brichard1638** [comment]
Hans:::

I am writing a book called "Conquering R Basics." I secured a publisher back in November 2020. The book should be released sometime in the next month or two. It is a work 5 years in the making. I am attempting to "redefine" what a basic understanding of R means.

If the R community accepts this work and/or I can get traction on the work publicly, I may be able to begin regular speaking engagements to discuss various aspects of R. I am already looking to write another book on the topic of R.

Either way, your work would definitely be on my list of things about which to speak in a talk about R. You have captured some really nice functions in the ds4psy package.

If I do speak or professionally write about anything related to your package, I will certainly inform you of the same.

Warm regards,

Brice
________________________________

**Comment by hneth** [comment]
Brice:::

this sounds intriguing — I'm looking forward to the book and am curious what redefining R basics will imply. 

Good luck with these efforts & best wishes,
Hans
